title: "Cyberbullying Detection"          
description: "CS 4641 Group 62"   
theme: jekyll-theme-cayman
url: "https://github.gatech.edu"                 
baseurl: "/pages/lpaschke3/lpaschke3.github.io"  

